name: HomePlugin
main: HomePluginSrc.Main
version: 1.0
api-version: 1.20
description: Plugin for setting, listing and teleporting to homes.
author: Philipp Maier aka UweDBG
commands:
  sethome:
    description: Sets a home at the players postition.
    usage: /sethome <Name>
  home:
    description: Teleports you to said home.
    usage: /home <Name>
  homes:
    description: Lists all your homes.
  delhome:
    description: Löscht ein gesetztes Home.
    usage: /delhome <Name>
